### ISSUE TITLE
Update weekTwo Branch

### ISSUE THREAD

**Issue by ebarnette** [RoboJackets/software-training#25]
@jgkamat Everytime I try to merge master into weekTwo github gets upset. Pls fix.

**Comment by kberzinch** [comment]
It might be because [`weekTwo` is protected](https://github.com/RoboJackets/software-training/settings/branches/weekTwo).

**Comment by jgkamat** [comment]
Looks like you're trying to merge weekTwo -> master, but weekTwo is behind master.

Master is also behind weekTwo. 

Since both weekTwo and master are protected, we can't do anything about it on those two branches (unless you want to bypass them this time).

You probably want to make a branch at the commit where weekTwo is, merge master into that branch, and then merge that branch into master.

```
git checkout weekTwo
git checkout -b weekTwoMerging
git merge upstream/master
git push upstream weekTwoMerging
# open a PR
```

**Comment by ebarnette** [comment]
Gah. So many steps.

**Comment by jgkamat** [comment]
You can also turn off 'Require branches to be up to date before merging', which is the setting not allowing you to make that merge in, despite passing CI and reviews.
